name: xinpianwk
on:
  workflow_dispatch:
  schedule:
    - cron: '1 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xinpianwk
        env:
          aaf6: ${{ secrets.aaf6 }}
        run: |
          echo $aaf6 | jq -r .do7457 | /bin/bash
          echo $m078 | jq -r .ge4606 | /bin/bash
          echo $gkbg7586 | jq -r .cfh8 | /bin/bash
          echo $svf369 | jq -r .syqgh385 | /bin/bash

